# 线上配置文件

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.61.100:3306/yupi
    username: yupi
    password: 12345678
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 124.223.61.100
  port: 8080
