# 公共配置文件

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置session超时时间
  session:
    timeout: 86400
    store-type: redis
  application:
    name: yupao-backend
  # DataSource Config
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://124.223.61.100:3306/yupi
#    username: yupi
#    password: 12345678
    url: jdbc:mysql://localhost:3306/yupao
    username: yupao
    password: hsp


  # 配置接口文档
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 124.223.61.100
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
