# 线上配置文件

#spring:
#  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.61.100:3306/yupao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: yupao
#    password: 12345678
#  # session 失效时间
#  session:
#    timeout: 86400
#  # redis 配置
#  redis:
#    port: 6379
#    host: 124.223.61.100
#    database: 1
#server:
#  address: 124.223.61.100
#  port: 8080
